### ISSUE TITLE
Font selection for Bold and BoldItalic is mixed up

### ISSUE THREAD

**Issue by moritzluedtke** [lusingander/fyne-theme-generator#3]
I like the app so far and it is a lot easier to make your own theme with it, so thanks a lot for making it!

I just discovered that the font selection for `bold` and `bold italic` is mixed up. You can also see it in the card widget titles. They are all italic. If you switch out the fonts manually and put a `bold italic` font in the selection for a `bold` font and the other way around it works properly.

![Bildschirmfoto 2021-03-05 um 10 30 29](https://user-images.githubusercontent.com/52150625/110096397-27256900-7d9e-11eb-8485-48dd168bf85b.png)

Vs how the app starts:
![Bildschirmfoto 2021-03-05 um 10 33 19](https://user-images.githubusercontent.com/52150625/110096481-3ad0cf80-7d9e-11eb-921c-d2a633a2d5bc.png)

**Edit:** But in the theme file it is correct. So I exported my theme file as shown in image 1 but the bold and bold italic fonts are mixed up. So the bug only seems to be in the ui.

**Comment by lusingander** [comment]
Thanks for catching this, and thanks for your interest!

**Comment by moritzluedtke** [comment]
Thanks a lot for the fast fix!
