### ISSUE TITLE
Generated font file still references Fyne v1 in the imports

### ISSUE THREAD

**Issue by moritzluedtke** [lusingander/fyne-theme-generator#4]
The generated font file still references Fyne v1. I don't know if this is intentional so I just want to share my finding with you.

In line 5 of `font_gen.go`:
```go
import "fyne.io/fyne"
```

**Comment by lusingander** [comment]
I think it's not correct, so fixed.

**Comment by moritzluedtke** [comment]
Again, thanks for the fast turnaround! :)
