### ISSUE TITLE
Reset to default theme

### ISSUE THREAD

**Issue by Lennart1978** [lusingander/fyne-theme-generator#9]
How can I reset to the standard Fyne default theme colors ? I changed some colors and now all my Fyne apps use these new colors. I didn't change the code of my Fyne programs, they all changed their colors now !

Regards,
Lennart

**Comment by lusingander** [comment]
Please explain in more detail what you did and what happened as a result.
This tool will output code for the theme, but I don't think it will change any settings.

**Comment by Lennart1978** [comment]
I started the Theme-generator and played around with some color settings. After that I clicked on "apply" and exited the program. And now the foreground color is changed on all my Fyne apps. For example the progress bars now have all bright green / green color instead of blue. How can I reset the color theme back to default ? I really didn't change anything else.

**Comment by lusingander** [comment]
- Does the problem reproduce?
  - If you have reproduced it, do you have a video or gif of it?
- What is the version (commit hash) of fyne-theme-generator?
- What is the Fyne version of your Fyne app?

**Comment by Lennart1978** [comment]
I don't know if the problem can be reproduced. I've only used the program once and now the foreground colors are wrong
and I can not change them anymore.
I installed the latest Theme Generator a couple of days ago with : "go install github.com/lusingander/fyne-theme-generator@latest".
I used Fyne Version: 2.4.2 for my apps.
Go Version: 1.21.3 - 1.21.5

Here is a screenshot: As you can see, the color changed from blue to green. All the other Fyne apps are the same.
![All_Green_Foreground](https://github.com/lusingander/fyne-theme-generator/assets/119766037/28583a66-ab69-4a7a-bedf-6622ca4b6adb)
